GET http://localhost:5000/pegawai

###
GET http://localhost:5000/pegawai/1

###
POST http://localhost:5000/pegawai
Content-Type: application/json

{
   "nik": "3304020212990005",
   "nama": "Kuat Dwi Prasetiyo",
   "tanggal_lahir": "1999-12-02",
   "tanggal_masuk": "1999-12-02",
   "alamat": "Jakarta"
}


###
PUT http://localhost:5000/pegawai/3304020212990002
Content-Type: application/json

{
   "nik": "3304020212990004",
   "nama": "Evy Rahmadhani",
   "tanggal_lahir": "1999-12-02",
   "tanggal_masuk": "1999-12-02",
   "alamat": "Jakarta"
}


###
DELETE http://localhost:5000/pegawai/3304020212990005