GET http://localhost:5000/pegawai?filter=3

###
GET http://localhost:5000/pegawai/

###
POST http://localhost:5000/pegawai
Content-Type: application/json

{
   "nik": "5",
   "nama": "Brata Putra Hanggara",
   "tanggal_lahir": "1995-12-02",
   "tanggal_masuk": "2021-12-02",
   "alamat": "Jakarta"
}


###
PUT http://localhost:5000/pegawai/1
Content-Type: application/json

{
   "nik": "99",
   "nama": "Brata Putra sak",
   "tanggal_lahir": "1999-12-02",
   "tanggal_masuk": "1999-12-02",
   "alamat": "Jakarta"
}


###
DELETE http://localhost:5000/pegawai/2